#!/usr/bin/env python3
"""Regenerates the embedded @font-face block in index.html.

Development only. `index.html` stays buildless: this writes base64 woff2 into it
once and the result is committed, so the shipped file still opens from file://
with no build step and no network. Nothing in the application calls this.

    pip install fonttools brotli
    python3 tools/fonts.py --report     # coverage table, writes nothing
    python3 tools/fonts.py --write      # splice into index.html

Why apt rather than Google Fonts or Fontsource: both of those serve *subsets*.
A Google "latin" woff2 has no block elements, no box drawing and no braille,
which are exactly the glyphs ASCII art needs — embedding one would silently
shear the grid on half the charsets. The Ubuntu archive ships the upstream
files intact, so that is where these come from.

Only families under a licence that permits redistribution embedded are listed.
Consolas, Menlo, Monaco, SF Mono, Andale Mono and Lucida Console are deliberately
absent: they are proprietary system faces and no file-size budget changes that.
The catalogue offers open replacements for each instead.
"""
import argparse, base64, io, os, re, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
INDEX = os.path.join(HERE, '..', 'index.html')

# key, CSS family, apt package, filename, licence
FAMILIES = [
    ('cascadia-mono', 'Cascadia Mono',    'fonts-cascadia-code',  'CascadiaMono.ttf',           'OFL-1.1'),
    ('cascadia-code', 'Cascadia Code',    'fonts-cascadia-code',  'CascadiaCode.ttf',           'OFL-1.1'),
    ('dejavu-mono',   'DejaVu Sans Mono', 'fonts-dejavu-mono',    'DejaVuSansMono.ttf',         'Bitstream Vera'),
    ('jetbrains',     'JetBrains Mono',   'fonts-jetbrains-mono', 'JetBrainsMono-Regular.ttf',  'OFL-1.1'),
    ('fira-code',     'Fira Code',        'fonts-firacode',       'FiraCode-Regular.ttf',       'OFL-1.1'),
    ('hack',          'Hack',             'fonts-hack',           'Hack-Regular.ttf',           'MIT / Bitstream Vera'),
    ('liberation',    'Liberation Mono',  'fonts-liberation',     'LiberationMono-Regular.ttf', 'OFL-1.1'),
    ('inconsolata',   'Inconsolata',      'fonts-inconsolata',    'Inconsolata.otf',            'OFL-1.1'),
    ('ubuntu-mono',   'Ubuntu Mono',      'fonts-ubuntu',         'UbuntuMono[wght].ttf',       'UFL-1.0'),
    ('noto-mono',     'Noto Sans Mono',   'fonts-noto-mono',      'NotoSansMono-Regular.ttf',   'OFL-1.1'),
    ('free-mono',     'GNU FreeMono',     'fonts-freefont-ttf',   'FreeMono.ttf',               'GPL-3.0 + font exception'),
    ('unifont',       'GNU Unifont',      'fonts-unifont',        'unifont.otf',                'OFL-1.1 / GPL + exception'),
]

# The ranges the tool reports on, and that the picker facets by. These are the
# glyphs ASCII art actually reaches for; latin coverage is table stakes.
RANGES = {
    'ascii':   (0x0020, 0x007E),
    'shade':   (0x2591, 0x2593),
    'blocks':  (0x2580, 0x259F),
    'boxdraw': (0x2500, 0x257F),
    'geom':    (0x25A0, 0x25FF),
    'braille': (0x2800, 0x28FF),
    'ogham':   (0x1680, 0x169C),
    'runic':   (0x16A0, 0x16F0),
}

BEGIN = '/* ==== EMBEDDED FONTS: generated by tools/fonts.py — do not hand-edit ==== */'
END = '/* ==== end embedded fonts ==== */'
JS_BEGIN = '/* ==== EMBEDDED FONT COVERAGE: generated by tools/fonts.py — do not hand-edit ==== */'
JS_END = '/* ==== end embedded font coverage ==== */'


def fetch(workdir):
    """apt-get download every package once, unpack into workdir/ex."""
    pkgs = sorted({p for _, _, p, _, _ in FAMILIES})
    deb = os.path.join(workdir, 'deb')
    os.makedirs(deb, exist_ok=True)
    have = {f.split('_')[0] for f in os.listdir(deb) if f.endswith('.deb')}
    todo = [p for p in pkgs if p not in have]
    if todo:
        subprocess.run(['apt-get', 'download', *todo], cwd=deb, check=True,
                       stdout=subprocess.DEVNULL)
    ex = os.path.join(deb, 'ex')
    for f in os.listdir(deb):
        if f.endswith('.deb'):
            subprocess.run(['dpkg-deb', '-x', f, 'ex'], cwd=deb, check=True)
    return ex


def find(ex, filename):
    for root, _, files in os.walk(ex):
        if filename in files:
            return os.path.join(root, filename)
    return None


def coverage(font):
    cmap = set(font.getBestCmap().keys())
    out = {}
    for name, (a, b) in RANGES.items():
        present = sum(1 for c in range(a, b + 1) if c in cmap)
        # unassigned code points inside a block would make "full" unreachable,
        # so score against what the font could plausibly carry, not the span
        out[name] = (present, b - a + 1)
    return out


def advances(font, lo, hi):
    """Distinct advance widths across a range — a set with one entry is a range
    that will hold the monospace grid, which is the whole question for a ramp."""
    cmap, hmtx = font.getBestCmap(), font['hmtx']
    return sorted({hmtx[cmap[c]][0] for c in range(lo, hi + 1) if c in cmap})


def load(path):
    from fontTools.ttLib import TTFont
    font = TTFont(path, fontNumber=0)
    if 'fvar' in font:
        # a variable font would need a weight range in the @font-face rule and
        # would ship every master; pin the regular instance instead
        from fontTools.varLib import instancer
        font = instancer.instantiateVariableFont(font, {'wght': 400})
    return font


def to_woff2(font):
    font.flavor = 'woff2'
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def build(ex, report_only):
    rows, faces, cover = [], [], {}
    for key, family, pkg, filename, licence in FAMILIES:
        path = find(ex, filename)
        if not path:
            rows.append((family, None, None, f'MISSING from {pkg}'))
            continue
        font = load(path)
        cov = coverage(font)
        data = None if report_only else to_woff2(font)
        rows.append((family, cov, len(data) if data else os.path.getsize(path), licence))
        # The browser cannot measure this reliably. Comparing a glyph's advance
        # to 'M' answers "is it the same width", not "does the font have it" —
        # which reports Ogham as absent from Unifont (it is there, and correctly
        # double-width) and present in latin-only faces (it is a fallback). For
        # an embedded family the file *is* the answer, so ship it.
        cover[family] = {k: int(have == tot) for k, (have, tot) in cov.items()}
        if data:
            b64 = base64.b64encode(data).decode('ascii')
            faces.append(
                f"  @font-face{{\n"
                f"    font-family:'{family}'; font-style:normal; font-weight:400; font-display:swap;\n"
                f"    src:url(data:font/woff2;base64,{b64}) format('woff2');\n"
                f"  }}"
            )
    return rows, faces, cover


def print_report(rows):
    keys = list(RANGES)
    print(f"{'family':20} {'size':>7}  " + '  '.join(f'{k:>7}' for k in keys))
    for family, cov, size, note in rows:
        if cov is None:
            print(f'{family:20} {"—":>7}  {note}')
            continue
        cells = []
        for k in keys:
            have, tot = cov[k]
            cells.append('full' if have == tot else (str(have) if have else '—'))
        print(f'{family:20} {size//1024:>6}K  ' + '  '.join(f'{c:>7}' for c in cells) + f'   {note}')


def splice(faces, cover):
    with open(INDEX, encoding='utf-8') as fh:
        html = fh.read()
    block = BEGIN + '\n' + '\n'.join(faces) + '\n  ' + END
    if BEGIN not in html:
        raise SystemExit('CSS markers not found in index.html — add them inside <style> first')
    html = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: block, html, flags=re.S)

    entries = ',\n'.join(
        "  '%s':{%s}" % (fam, ','.join(f'{k}:{v}' for k, v in flags.items() if v))
        for fam, flags in cover.items())
    js = JS_BEGIN + '\nconst FONT_COVER = {\n' + entries + ',\n};\n' + JS_END
    if JS_BEGIN not in html:
        raise SystemExit('JS markers not found in index.html — add them in the font catalogue first')
    html = re.sub(re.escape(JS_BEGIN) + r'.*?' + re.escape(JS_END), lambda _: js, html, flags=re.S)
    with open(INDEX, 'w', encoding='utf-8') as fh:
        fh.write(html)
    print(f'\nwrote {len(faces)} @font-face rules into index.html '
          f'({os.path.getsize(INDEX)/1e6:.2f} MB)')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--write', action='store_true', help='splice into index.html')
    ap.add_argument('--report', action='store_true', help='coverage table only')
    ap.add_argument('--workdir', default=os.path.join(tempfile.gettempdir(), 'grit-fonts'))
    args = ap.parse_args()
    os.makedirs(args.workdir, exist_ok=True)
    ex = fetch(args.workdir)
    rows, faces, cover = build(ex, report_only=args.report and not args.write)
    print_report(rows)
    if args.write:
        splice(faces, cover)


if __name__ == '__main__':
    main()
